// Static seed content: amenities, demo users and realistic Indian listings.
//
// prisma/seed.ts references PROPERTIES by array index (favourites, offers, the reserved and sold
// flows, notifications, audit rows). Keep the owner / listingType / status role of each index
// stable when editing, and append new listings at the end.

export const AMENITIES = [
  { slug: "air-conditioning", name: "Air conditioning", category: "Comfort" },
  { slug: "power-backup", name: "24x7 power backup", category: "Comfort" },
  { slug: "water-supply", name: "24x7 water supply", category: "Comfort" },
  { slug: "piped-gas", name: "Piped gas", category: "Comfort" },
  { slug: "modular-kitchen", name: "Modular kitchen", category: "Interior" },
  { slug: "wardrobes", name: "Built-in wardrobes", category: "Interior" },
  { slug: "pooja-room", name: "Pooja room", category: "Interior" },
  { slug: "servant-room", name: "Servant room", category: "Interior" },
  { slug: "home-office", name: "Study / home office", category: "Interior" },
  { slug: "vastu-compliant", name: "Vastu compliant", category: "Interior" },
  { slug: "car-parking", name: "Covered car parking", category: "Outdoor" },
  { slug: "garden", name: "Garden", category: "Outdoor" },
  { slug: "balcony", name: "Balcony", category: "Outdoor" },
  { slug: "terrace", name: "Terrace", category: "Outdoor" },
  { slug: "swimming-pool", name: "Swimming pool", category: "Outdoor" },
  { slug: "ev-charging", name: "EV charging point", category: "Outdoor" },
  { slug: "lift", name: "Lift", category: "Society" },
  { slug: "clubhouse", name: "Clubhouse", category: "Society" },
  { slug: "gym", name: "Gym", category: "Society" },
  { slug: "childrens-play-area", name: "Children's play area", category: "Society" },
  { slug: "gated-security", name: "Gated security with CCTV", category: "Society" },
  { slug: "intercom", name: "Intercom", category: "Society" },
  { slug: "visitor-parking", name: "Visitor parking", category: "Society" },
  { slug: "rainwater-harvesting", name: "Rainwater harvesting", category: "Society" },
  { slug: "pet-friendly", name: "Pet friendly", category: "Lifestyle" },
  { slug: "solar-panels", name: "Solar panels", category: "Lifestyle" },
  { slug: "high-speed-internet", name: "High-speed internet", category: "Lifestyle" },
  { slug: "sea-view", name: "Sea / lake view", category: "Lifestyle" },
  { slug: "corner-plot", name: "Corner plot", category: "Plot" },
  { slug: "compound-wall", name: "Compound wall", category: "Plot" },
  { slug: "road-access", name: "Wide road access", category: "Plot" },
  { slug: "borewell", name: "Borewell", category: "Plot" },
];

export type SeedUser = {
  key: string;
  name: string;
  email: string;
  role: "BUYER" | "SELLER" | "AGENT" | "ADMIN";
  verified: boolean;
  status?: "ACTIVE" | "SUSPENDED";
  profile: { phone?: string; bio?: string; company?: string; location?: string; website?: string };
};

export const USERS: SeedUser[] = [
  {
    key: "admin",
    name: "Aarav Admin",
    email: "admin@doorkey.local",
    role: "ADMIN",
    verified: true,
    profile: { location: "Remote", bio: "Platform administrator for the Doorkey Realty demo.", company: "Doorkey Realty" },
  },
  {
    key: "meera",
    name: "Meera Iyer",
    email: "meera.iyer@doorkey.local",
    role: "SELLER",
    verified: true,
    profile: { phone: "+91 98450 12345", location: "Bengaluru, Karnataka", bio: "Selling the family homes we have lovingly maintained over the years. Fast, honest replies on calls and WhatsApp." },
  },
  {
    key: "rohan",
    name: "Rohan Mehta",
    email: "rohan.mehta@doorkey.local",
    role: "AGENT",
    verified: true,
    profile: { phone: "+91 98200 45678", company: "Mehta Estates", location: "Pune, Maharashtra", website: "https://example.com/mehta-estates", bio: "RERA-registered agent with 12 years in the Pune market. Specialising in family homes, row houses and plots." },
  },
  {
    key: "kavya",
    name: "Kavya Reddy",
    email: "kavya.reddy@doorkey.local",
    role: "SELLER",
    verified: true,
    profile: { phone: "+91 99490 23456", location: "Hyderabad, Telangana", bio: "Architect turned landlord. My rentals are energy efficient and pet friendly." },
  },
  {
    key: "arjun",
    name: "Arjun Nair",
    email: "arjun.nair@doorkey.local",
    role: "AGENT",
    verified: true,
    profile: { phone: "+91 98400 56789", company: "Nair & Co Realty", location: "Chennai, Tamil Nadu", website: "https://example.com/nair-realty", bio: "Boutique agency covering Chennai, Kochi and Mumbai sea-facing properties." },
  },
  {
    key: "priya",
    name: "Priya Menon",
    email: "priya.menon@doorkey.local",
    role: "BUYER",
    verified: true,
    profile: { phone: "+91 98450 67890", location: "Bengaluru, Karnataka", bio: "First-time buyer looking for a 3 BHK with a garden." },
  },
  {
    key: "vikram",
    name: "Vikram Singh",
    email: "vikram.singh@doorkey.local",
    role: "BUYER",
    verified: true,
    profile: { location: "Pune, Maharashtra", bio: "Relocating for work - need somewhere with a home office and fast internet." },
  },
  {
    key: "sneha",
    name: "Sneha Kulkarni",
    email: "sneha.kulkarni@doorkey.local",
    role: "BUYER",
    verified: true,
    profile: { location: "Mumbai, Maharashtra", bio: "Investor comparing rental yields across Mumbai, Pune and Chennai." },
  },
  {
    key: "karthik",
    name: "Karthik Raman",
    email: "karthik.raman@doorkey.local",
    role: "BUYER",
    verified: true,
    profile: { location: "Chennai, Tamil Nadu" },
  },
  {
    key: "newbie",
    name: "Neha Verma",
    email: "new.user@doorkey.local",
    role: "BUYER",
    verified: false,
    profile: {},
  },
  {
    key: "suspended",
    name: "Sunil Spammer",
    email: "suspended@doorkey.local",
    role: "SELLER",
    verified: true,
    status: "SUSPENDED",
    profile: { location: "Unknown" },
  },
];

export type SeedProperty = {
  owner: string;
  title: string;
  description: string;
  listingType: "SALE" | "RENT";
  propertyType: "HOUSE" | "APARTMENT" | "TOWNHOUSE" | "PLOT_RESIDENTIAL" | "PLOT_COMMERCIAL" | "PLOT_SEMI_COMMERCIAL" | "PLOT_INDUSTRIAL" | "COMMERCIAL" | "OTHER";
  status: "DRAFT" | "PENDING_REVIEW" | "ACTIVE" | "UNDER_OFFER" | "RESERVED" | "SOLD" | "RENTED" | "REJECTED" | "ARCHIVED";
  price: number;
  deposit: number;
  address: string;
  city: string;
  state: string;
  postalCode: string;
  lat: number;
  lng: number;
  bedrooms: number;
  bathrooms: number;
  parking: number;
  interiorArea: number | null;
  lotArea: number | null;
  yearBuilt: number | null;
  furnished: "UNFURNISHED" | "SEMI_FURNISHED" | "FURNISHED";
  amenities: string[];
  featured?: boolean;
  images: number;
  views: number;
  daysAgo: number;
  rejectionReason?: string;
};

const p = (input: SeedProperty) => input;

// Prices are in rupees (sale price, or rent per month). Areas are in sq ft.
export const PROPERTIES: SeedProperty[] = [
  // 0 - meera, featured sale, pending offer from priya
  p({
    owner: "meera",
    title: "Sunlit 3 BHK independent house with a private garden in JP Nagar",
    description:
      "A lovingly maintained 1998 independent house on a quiet, tree-lined road in JP Nagar 7th Phase. Vitrified flooring runs through the light-filled living room and into a modular kitchen with granite counters, a chimney and a separate utility area.\n\nThree generous bedrooms upstairs share a spacious bathroom, while the ground floor has a second bathroom, a pooja room and a flexible study that works as a home office. Outside, a deep private garden with a mature mango tree, a covered sit-out and a two-car porch with an EV charging point.\n\nWalk to Sarakki Lake, the vegetable market and two well-rated schools. A-khata, BWSSB Cauvery water connection and borewell. Roof waterproofed in 2022.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 18500000,
    deposit: 100000,
    address: "No. 412, 24th Main, JP Nagar 7th Phase",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560078",
    lat: 12.9063,
    lng: 77.5857,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    interiorArea: 2100,
    lotArea: 2400,
    yearBuilt: 1998,
    furnished: "UNFURNISHED",
    amenities: ["modular-kitchen", "pooja-room", "garden", "car-parking", "ev-charging", "home-office", "air-conditioning", "borewell"],
    featured: true,
    images: 4,
    views: 412,
    daysAgo: 6,
  }),
  // 1 - meera, sale
  p({
    owner: "meera",
    title: "Modern 3 BHK row house with rooftop terrace in Whitefield",
    description:
      "Three-level end-unit row house built in 2019 inside a gated community off Varthur Main Road, with a private rooftop terrace and views over the lake. Open-plan living on the first floor with floor-to-ceiling windows, a modular kitchen and a powder room.\n\nTwo bedroom suites on the top floor, each with its own bathroom, plus a guest bedroom on the ground floor. Covered parking for two cars and a small side garden. Society maintenance covers security, landscaping and the clubhouse.",
    listingType: "SALE",
    propertyType: "TOWNHOUSE",
    status: "ACTIVE",
    price: 14500000,
    deposit: 75000,
    address: "Villa 22, Lakeview Enclave, Varthur Main Road, Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560066",
    lat: 12.9698,
    lng: 77.75,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    interiorArea: 1850,
    lotArea: 1200,
    yearBuilt: 2019,
    furnished: "SEMI_FURNISHED",
    amenities: ["terrace", "car-parking", "air-conditioning", "clubhouse", "gated-security", "high-speed-internet", "power-backup"],
    images: 3,
    views: 268,
    daysAgo: 12,
  }),
  // 2 - meera, sale
  p({
    owner: "meera",
    title: "Compact 1 BHK independent house near Lalbagh, Basavanagudi",
    description:
      "Charming one-bedroom independent house on a 20x30 site a short walk from Lalbagh's west gate. High ceilings, red-oxide flooring and a wooden-beamed living room give it real old-Bengaluru character. Updated kitchen and bathroom, and a covered verandah for morning coffee.\n\nPerfect starter home or a redevelopment opportunity with BBMP-approved plans possible. Off-street parking for one car.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 6800000,
    deposit: 50000,
    address: "No. 18, 3rd Cross, Hanumanthanagar, Basavanagudi",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560004",
    lat: 12.942,
    lng: 77.5737,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    interiorArea: 720,
    lotArea: 600,
    yearBuilt: 1972,
    furnished: "UNFURNISHED",
    amenities: ["car-parking", "water-supply", "vastu-compliant"],
    images: 3,
    views: 190,
    daysAgo: 19,
  }),
  // 3 - rohan, featured sale, countered offer from vikram
  p({
    owner: "rohan",
    title: "Koregaon Park bungalow with a lawn and a home office",
    description:
      "Classic 1980s bungalow on a leafy Koregaon Park lane, renovated in 2021 with a new kitchen, bathrooms and wiring. Four bedrooms including a first-floor primary suite with a private balcony, a separate study wired with fibre and a large family room opening onto the lawn.\n\nTwo covered car parks, a servant room with attached bath and a rainwater harvesting system. Gigabit fibre installed. Osho Garden, Lane 7 cafes and the airport road are minutes away.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 32000000,
    deposit: 150000,
    address: "Bungalow 9, Lane 5, Koregaon Park",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411001",
    lat: 18.5362,
    lng: 73.8939,
    bedrooms: 4,
    bathrooms: 4,
    parking: 2,
    interiorArea: 3400,
    lotArea: 5000,
    yearBuilt: 1984,
    furnished: "UNFURNISHED",
    amenities: ["garden", "home-office", "servant-room", "car-parking", "high-speed-internet", "rainwater-harvesting", "air-conditioning", "power-backup"],
    featured: true,
    images: 4,
    views: 655,
    daysAgo: 4,
  }),
  // 4 - rohan, sale, UNDER_OFFER (accepted offer from karthik, deposit not yet paid)
  p({
    owner: "rohan",
    title: "Kalyani Nagar loft apartment with exposed brick and river views",
    description:
      "Rare double-height loft in a boutique 2016 building on the Mula-Mutha riverfront: 14-foot ceilings, exposed brick, oversized windows and polished concrete floors. Open kitchen with a breakfast counter, a large bedroom with walk-in wardrobes and a spa-style bathroom.\n\nSociety has a rooftop deck, gym and 24-hour security. One covered car park. Phoenix Marketcity and the Kalyani Nagar bridge are two minutes away.",
    listingType: "SALE",
    propertyType: "APARTMENT",
    status: "UNDER_OFFER",
    price: 12500000,
    deposit: 75000,
    address: "Flat 402, Riverside Lofts, Kalyani Nagar",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411006",
    lat: 18.5481,
    lng: 73.904,
    bedrooms: 1,
    bathrooms: 1.5,
    parking: 1,
    interiorArea: 1240,
    lotArea: null,
    yearBuilt: 2016,
    furnished: "UNFURNISHED",
    amenities: ["lift", "gated-security", "gym", "car-parking", "high-speed-internet", "sea-view"],
    images: 3,
    views: 341,
    daysAgo: 25,
  }),
  // 5 - rohan, sale, expired offer from vikram
  p({
    owner: "rohan",
    title: "Renovated Aundh duplex - live in one floor, rent the other",
    description:
      "Rare independent duplex near Aundh's ITI Road with two self-contained 2 BHK units, each with its own entrance, kitchen and utility area. Fully renovated in 2021 with new waterproofing, windows, electrical and plumbing.\n\nCurrently one floor is owner-occupied and the other rents for ₹26,500/month. Ideal for a joint family or a long-term investment.",
    listingType: "SALE",
    propertyType: "OTHER",
    status: "ACTIVE",
    price: 21000000,
    deposit: 100000,
    address: "Plot 31, Sanewadi, Aundh",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411007",
    lat: 18.559,
    lng: 73.807,
    bedrooms: 4,
    bathrooms: 4,
    parking: 2,
    interiorArea: 2400,
    lotArea: 2000,
    yearBuilt: 1996,
    furnished: "UNFURNISHED",
    amenities: ["garden", "car-parking", "modular-kitchen", "power-backup"],
    images: 3,
    views: 223,
    daysAgo: 9,
  }),
  // 6 - rohan, residential plot
  p({
    owner: "rohan",
    title: "East-facing 40x60 residential plot in a gated layout, Hinjewadi Phase 3",
    description:
      "2,400 sq ft east-facing plot in an approved gated layout ten minutes from the Hinjewadi IT park. Tar roads, underground drainage, street lighting and electricity are already in place; water is from the layout's borewell and a Maharashtra Jeevan Pradhikaran connection.\n\nClear title with 7/12 extract and NA order available. Ideal for a 3 BHK villa; several neighbours have already built.",
    listingType: "SALE",
    propertyType: "PLOT_RESIDENTIAL",
    status: "ACTIVE",
    price: 9600000,
    deposit: 50000,
    address: "Plot 47, Sunrise Meadows Layout, Marunji Road, Hinjewadi Phase 3",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411057",
    lat: 18.5912,
    lng: 73.691,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    interiorArea: null,
    lotArea: 2400,
    yearBuilt: null,
    furnished: "UNFURNISHED",
    amenities: ["road-access", "compound-wall", "gated-security", "borewell"],
    images: 2,
    views: 148,
    daysAgo: 15,
  }),
  // 7 - kavya, featured rental, enquiry from karthik
  p({
    owner: "kavya",
    title: "Bright 2 BHK flat with clubhouse access in Gachibowli",
    description:
      "Twelfth-floor two-bedroom in a well-run 2018 gated society opposite the DLF Cybercity campus. Large living room with a balcony facing the greens, modular kitchen with chimney, and two attached bathrooms.\n\nSociety has a clubhouse, pool, gym and 24-hour security. One covered car park and 24x7 power backup included. Available from the 1st of next month; families and working professionals preferred.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 34500,
    deposit: 34500,
    address: "Flat 1204, Tower B, Aparna Cyber Heights, Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500032",
    lat: 17.4401,
    lng: 78.3489,
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    interiorArea: 1250,
    lotArea: null,
    yearBuilt: 2018,
    furnished: "SEMI_FURNISHED",
    amenities: ["balcony", "clubhouse", "swimming-pool", "gym", "lift", "gated-security", "power-backup", "car-parking", "pet-friendly"],
    featured: true,
    images: 4,
    views: 530,
    daysAgo: 3,
  }),
  // 8 - kavya, rental (dismissed duplicate report by vikram)
  p({
    owner: "kavya",
    title: "Furnished studio in Madhapur, all bills included",
    description:
      "Fully furnished studio two streets from Hitech City metro: queen bed, work desk, smart TV, kitchenette with induction hob and microwave, and a washing machine. Electricity, water, Wi-Fi and housekeeping once a week are included in the rent.\n\nIdeal for a working professional on a 6-11 month lease. Two-wheeler parking available.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 16500,
    deposit: 16500,
    address: "Unit 3B, Sri Sai Residency, Ayyappa Society Road, Madhapur",
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500081",
    lat: 17.4483,
    lng: 78.3915,
    bedrooms: 1,
    bathrooms: 1,
    parking: 0,
    interiorArea: 420,
    lotArea: null,
    yearBuilt: 2014,
    furnished: "FURNISHED",
    amenities: ["air-conditioning", "high-speed-internet", "power-backup", "lift"],
    images: 3,
    views: 288,
    daysAgo: 8,
  }),
  // 9 - kavya, rental house (archived connection with vikram)
  p({
    owner: "kavya",
    title: "Energy-efficient 3 BHK villa in a gated community, Kondapur",
    description:
      "Architect-designed villa with rooftop solar, rainwater harvesting and cross-ventilation that keeps the summer electricity bill under ₹2,500. Three bedrooms, a study, a modular kitchen with chimney and a private garden with a covered sit-out.\n\nGated community with a pool, gym and children's play area. Two covered car parks. Pets welcome.",
    listingType: "RENT",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 45000,
    deposit: 45000,
    address: "Villa 14, Green Acres, Botanical Garden Road, Kondapur",
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500084",
    lat: 17.4647,
    lng: 78.3639,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    interiorArea: 2200,
    lotArea: 1800,
    yearBuilt: 2017,
    furnished: "UNFURNISHED",
    amenities: ["solar-panels", "rainwater-harvesting", "garden", "home-office", "car-parking", "swimming-pool", "childrens-play-area", "pet-friendly", "gated-security"],
    images: 3,
    views: 201,
    daysAgo: 11,
  }),
  // 10 - kavya, RENTED
  p({
    owner: "kavya",
    title: "Lake-facing 1 BHK with balcony in Hitech City",
    description:
      "Twelfth-floor one-bedroom with a west-facing balcony over Durgam Cheruvu. Modular kitchen, wardrobes, washing machine point and a large bathroom. Society has 24-hour security, gym, and covered parking.\n\nCurrently tenanted; available from the first of next month.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "RENTED",
    price: 22000,
    deposit: 22000,
    address: "Flat 1207, Lakeshore Towers, Inorbit Mall Road, Hitech City",
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500081",
    lat: 17.4435,
    lng: 78.3772,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    interiorArea: 760,
    lotArea: null,
    yearBuilt: 2012,
    furnished: "SEMI_FURNISHED",
    amenities: ["balcony", "gym", "lift", "sea-view", "gated-security", "car-parking"],
    images: 2,
    views: 411,
    daysAgo: 60,
  }),
  // 11 - arjun, featured sale, rejected offer from karthik
  p({
    owner: "arjun",
    title: "Besant Nagar sea-view bungalow with a chef's kitchen",
    description:
      "Classic 1985 bungalow two streets from Elliot's Beach with sweeping views of the Bay of Bengal from the first-floor terrace. Restored period details - teak doors, Athangudi tiles, a curved staircase - paired with a fully modern kitchen and wiring.\n\nFour bedrooms including a top-floor primary suite with a private deck. Ground floor has a family room, a pooja room and a separate-entrance guest suite. Two covered car parks. Roof and plumbing new in 2023.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 68000000,
    deposit: 200000,
    address: "No. 7, 4th Avenue, Besant Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    postalCode: "600090",
    lat: 13.0002,
    lng: 80.2668,
    bedrooms: 4,
    bathrooms: 4,
    parking: 2,
    interiorArea: 3900,
    lotArea: 4800,
    yearBuilt: 1985,
    furnished: "UNFURNISHED",
    amenities: ["sea-view", "pooja-room", "car-parking", "modular-kitchen", "garden", "gated-security", "air-conditioning", "power-backup"],
    featured: true,
    images: 4,
    views: 902,
    daysAgo: 2,
  }),
  // 12 - arjun, sale (closed enquiry from karthik)
  p({
    owner: "arjun",
    title: "Adyar 2 BHK flat, walk to the metro",
    description:
      "Top-floor two-bedroom in a well-run 2006 building on a quiet Adyar street. High ceilings, a private balcony and a bright open kitchen. Both bedrooms fit king beds; the primary has an attached bathroom.\n\nAssociation maintenance covers water, lift, security and generator backup. Covered car park and a storage room. Metro station, Adyar Bakery and dozens of restaurants within five minutes.",
    listingType: "SALE",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 13500000,
    deposit: 75000,
    address: "Flat 5A, Shanthi Apartments, 2nd Main Road, Gandhi Nagar, Adyar",
    city: "Chennai",
    state: "Tamil Nadu",
    postalCode: "600020",
    lat: 13.0067,
    lng: 80.257,
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    interiorArea: 1080,
    lotArea: null,
    yearBuilt: 2006,
    furnished: "UNFURNISHED",
    amenities: ["balcony", "lift", "car-parking", "power-backup", "pet-friendly", "water-supply"],
    images: 3,
    views: 377,
    daysAgo: 11,
  }),
  // 13 - arjun, sale
  p({
    owner: "arjun",
    title: "Sholinganallur row house with rooftop deck on the OMR",
    description:
      "Light-filled 2020 row house with a private rooftop deck in a gated community off Old Mahabalipuram Road. Three levels: covered parking and a flex room, open-plan living with a balcony, and two bedroom suites up top. Inverter backup, solar water heater and an EV-ready car park.\n\nClubhouse, pool and gym in the community. Walk to the IT corridor offices, ECR beaches are a fifteen-minute drive.",
    listingType: "SALE",
    propertyType: "TOWNHOUSE",
    status: "ACTIVE",
    price: 16500000,
    deposit: 100000,
    address: "Row House 17, Palm Grove, Sholinganallur",
    city: "Chennai",
    state: "Tamil Nadu",
    postalCode: "600119",
    lat: 12.901,
    lng: 80.2279,
    bedrooms: 3,
    bathrooms: 3,
    parking: 1,
    interiorArea: 1690,
    lotArea: 1000,
    yearBuilt: 2020,
    furnished: "UNFURNISHED",
    amenities: ["terrace", "balcony", "car-parking", "ev-charging", "air-conditioning", "clubhouse", "swimming-pool", "gated-security"],
    images: 3,
    views: 254,
    daysAgo: 17,
  }),
  // 14 - arjun, RESERVED (accepted offer + paid deposit from sneha)
  p({
    owner: "arjun",
    title: "Marine Drive sea-view flat with resort amenities, Kochi",
    description:
      "Fully furnished two-bedroom on the fourth floor of a waterfront community on Marine Drive. Wake up to backwater views from the bedroom and living room, and watch the sunset from the covered balcony.\n\nRemodelled in 2022 with a modular kitchen, wide-plank flooring and spa bathrooms. Community features two pools, tennis courts, a gym and gated parking. Perfect second home or turnkey rental.",
    listingType: "SALE",
    propertyType: "APARTMENT",
    status: "RESERVED",
    price: 24000000,
    deposit: 150000,
    address: "Flat 4F, Bayview Residency, Marine Drive",
    city: "Kochi",
    state: "Kerala",
    postalCode: "682031",
    lat: 9.9777,
    lng: 76.2757,
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    interiorArea: 1380,
    lotArea: null,
    yearBuilt: 2008,
    furnished: "FURNISHED",
    amenities: ["sea-view", "swimming-pool", "gym", "balcony", "lift", "gated-security", "air-conditioning", "car-parking"],
    images: 4,
    views: 645,
    daysAgo: 40,
  }),
  // 15 - arjun, sale
  p({
    owner: "arjun",
    title: "Kakkanad independent house with a separate outhouse",
    description:
      "Kerala-style independent house on a corner plot in Kakkanad with a separate one-bedroom outhouse (currently rented at ₹9,000/month). Main house has three bedrooms, an updated kitchen with a traditional work area, a pooja room and a sit-out with pillared verandah.\n\nWell and Kerala Water Authority connection, a coconut grove and a covered patio. Infopark, Lulu Mall and the metro are within twenty minutes.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 17500000,
    deposit: 100000,
    address: "House 33, Thengode Road, Kakkanad",
    city: "Kochi",
    state: "Kerala",
    postalCode: "682030",
    lat: 10.0159,
    lng: 76.3419,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    interiorArea: 2150,
    lotArea: 4350,
    yearBuilt: 1994,
    furnished: "UNFURNISHED",
    amenities: ["pooja-room", "garden", "modular-kitchen", "car-parking", "pet-friendly", "corner-plot", "borewell"],
    images: 3,
    views: 318,
    daysAgo: 7,
  }),
  // 16 - arjun, featured rental (enquiry + conversation with sneha)
  p({
    owner: "arjun",
    title: "Lower Parel high-rise 1 BHK with sea views",
    description:
      "Thirty-second-floor one-bedroom in a 2019 tower with floor-to-ceiling windows and views of the Arabian Sea and the Bandra-Worli Sea Link. Modular kitchen, wardrobes and a spa bathroom. The society has an infinity pool, gym, valet parking and 24-hour concierge.\n\nWalk to the Phoenix Palladium mall and the Lower Parel and Prabhadevi stations. Unfurnished; one car park included.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 85000,
    deposit: 85000,
    address: "Flat 3204, Skyline One, Senapati Bapat Marg, Lower Parel",
    city: "Mumbai",
    state: "Maharashtra",
    postalCode: "400013",
    lat: 18.9964,
    lng: 72.83,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    interiorArea: 720,
    lotArea: null,
    yearBuilt: 2019,
    furnished: "UNFURNISHED",
    amenities: ["sea-view", "swimming-pool", "gym", "lift", "gated-security", "intercom", "car-parking", "air-conditioning"],
    featured: true,
    images: 3,
    views: 812,
    daysAgo: 5,
  }),
  // 17 - arjun, sale, withdrawn offer from sneha
  p({
    owner: "arjun",
    title: "Juhu villa with a private pool and garden",
    description:
      "Rare independent villa on a quiet Juhu lane, five minutes from the beach. Five bedrooms across two floors, a double-height living room, a formal dining room and a modern kitchen with a separate wet kitchen.\n\nLandscaped garden with a heated pool, an outdoor shower and a covered deck. Servant quarters, four covered car parks and a generator. Clear title, OC available.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 185000000,
    deposit: 200000,
    address: "Villa 3, Gulmohar Road, JVPD Scheme, Juhu",
    city: "Mumbai",
    state: "Maharashtra",
    postalCode: "400049",
    lat: 19.1075,
    lng: 72.8263,
    bedrooms: 5,
    bathrooms: 5,
    parking: 4,
    interiorArea: 5200,
    lotArea: 6000,
    yearBuilt: 2004,
    furnished: "SEMI_FURNISHED",
    amenities: ["swimming-pool", "garden", "servant-room", "car-parking", "air-conditioning", "power-backup", "gated-security", "terrace"],
    images: 4,
    views: 1104,
    daysAgo: 21,
  }),
  // 18 - meera, sale
  p({
    owner: "meera",
    title: "Heritage-style cottage with a music room in Yadavagiri, Mysuru",
    description:
      "Charming single-storey cottage on a wide, quiet road in Yadavagiri with Mangalore-tiled roof and a wraparound verandah. The former garage has been converted into a sound-treated music room that also works as a studio or office.\n\nThree bedrooms, a renovated kitchen, solar water heating and a garden full of jackfruit and jasmine. Ten minutes to the palace and the railway station.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 8900000,
    deposit: 50000,
    address: "No. 101, Vivekananda Road, Yadavagiri",
    city: "Mysuru",
    state: "Karnataka",
    postalCode: "570020",
    lat: 12.32,
    lng: 76.635,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    interiorArea: 1650,
    lotArea: 3600,
    yearBuilt: 1962,
    furnished: "UNFURNISHED",
    amenities: ["garden", "home-office", "solar-panels", "car-parking", "vastu-compliant"],
    images: 3,
    views: 176,
    daysAgo: 13,
  }),
  // 19 - rohan, commercial sale (open report from sneha)
  p({
    owner: "rohan",
    title: "Fully leased 3-unit building in Viman Nagar - investment",
    description:
      "Three-storey commercial building on a 2,500 sq ft plot in Viman Nagar with a ground-floor showroom and two office floors, all on 5-year leases to established tenants. Gross annual rent of ₹34,80,000 with 5% annual escalation.\n\nLift, generator backup, eight car parks and a separate staircase for the upper floors. Two minutes from Phoenix Marketcity and the airport road.",
    listingType: "SALE",
    propertyType: "COMMERCIAL",
    status: "ACTIVE",
    price: 38000000,
    deposit: 150000,
    address: "Plot 88, Clover Park Road, Viman Nagar",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411014",
    lat: 18.5679,
    lng: 73.9143,
    bedrooms: 0,
    bathrooms: 4,
    parking: 8,
    interiorArea: 6000,
    lotArea: 2500,
    yearBuilt: 2011,
    furnished: "UNFURNISHED",
    amenities: ["lift", "power-backup", "car-parking", "gated-security", "road-access"],
    images: 3,
    views: 266,
    daysAgo: 16,
  }),
  // 20 - rohan, SOLD (completed reservation with vikram)
  p({
    owner: "rohan",
    title: "Baner penthouse with a private terrace",
    description:
      "Three-bedroom penthouse in a boutique Baner building with a 600 sq ft private terrace and views towards the hills. Ten-foot ceilings, wooden flooring, a modular kitchen with premium appliances and a primary suite with a soaking tub.\n\nTwo covered car parks included. Steps from Baner Road cafes and the Balewadi High Street.",
    listingType: "SALE",
    propertyType: "APARTMENT",
    status: "SOLD",
    price: 27500000,
    deposit: 150000,
    address: "Penthouse 2, Vista Heights, Baner Road",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411045",
    lat: 18.559,
    lng: 73.7868,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    interiorArea: 1900,
    lotArea: null,
    yearBuilt: 2017,
    furnished: "UNFURNISHED",
    amenities: ["terrace", "lift", "car-parking", "modular-kitchen", "gated-security", "power-backup"],
    images: 3,
    views: 720,
    daysAgo: 75,
  }),
  // 21 - kavya, rental
  p({
    owner: "kavya",
    title: "Banjara Hills 1 BHK garden flat",
    description:
      "Ground-floor one-bedroom in a low-rise Banjara Hills building with a private patio. Tall windows, a decorative brick wall and an updated galley kitchen. Shared laundry and a storage cupboard.\n\nWater and maintenance included. Walk to KBR Park, Road No. 12 restaurants and the Jubilee Hills check post.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 28000,
    deposit: 28000,
    address: "Flat G-2, Rock Castle Apartments, Road No. 10, Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500034",
    lat: 17.4156,
    lng: 78.4347,
    bedrooms: 1,
    bathrooms: 1,
    parking: 0,
    interiorArea: 680,
    lotArea: null,
    yearBuilt: 1998,
    furnished: "SEMI_FURNISHED",
    amenities: ["garden", "water-supply", "power-backup", "pet-friendly"],
    images: 2,
    views: 344,
    daysAgo: 10,
  }),
  // 22 - meera, PENDING_REVIEW
  p({
    owner: "meera",
    title: "Devanahalli farmhouse with a guest cottage and hill views",
    description:
      "One-acre farmhouse fifteen minutes from Kempegowda International Airport with views of the Nandi Hills. Single-level main house with three bedrooms, a large living-dining room with a wood-burning fireplace and a covered outdoor kitchen. Separate one-bedroom guest cottage by the pool.\n\nMango and coconut plantation, drip irrigation, borewell and a 10 kW solar array. Ideal weekend home or boutique-stay opportunity.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "PENDING_REVIEW",
    price: 42000000,
    deposit: 200000,
    address: "Sy. No. 42, Vishwanathapura Road, Devanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "562110",
    lat: 13.2437,
    lng: 77.713,
    bedrooms: 4,
    bathrooms: 4,
    parking: 3,
    interiorArea: 3200,
    lotArea: 43560,
    yearBuilt: 2015,
    furnished: "SEMI_FURNISHED",
    amenities: ["swimming-pool", "garden", "solar-panels", "borewell", "car-parking", "compound-wall"],
    images: 3,
    views: 0,
    daysAgo: 1,
  }),
  // 23 - arjun, commercial rental, PENDING_REVIEW
  p({
    owner: "arjun",
    title: "Andheri East office studio near the metro",
    description:
      "Ground-floor 1,100 sq ft office space in a commercial complex on Andheri-Kurla Road: open-plan work area, a glass-partitioned cabin, a pantry and an attached washroom. Fresh paint, false ceiling and LED lighting.\n\nTwo minutes from Marol Naka metro station. Suits a startup, clinic or design studio. Three-year lease preferred.",
    listingType: "RENT",
    propertyType: "COMMERCIAL",
    status: "PENDING_REVIEW",
    price: 65000,
    deposit: 65000,
    address: "Unit 4, Solitaire Corporate Park, Andheri-Kurla Road, Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    postalCode: "400093",
    lat: 19.1136,
    lng: 72.8697,
    bedrooms: 0,
    bathrooms: 1,
    parking: 1,
    interiorArea: 1100,
    lotArea: null,
    yearBuilt: 2009,
    furnished: "SEMI_FURNISHED",
    amenities: ["air-conditioning", "lift", "power-backup", "high-speed-internet", "car-parking"],
    images: 2,
    views: 0,
    daysAgo: 1,
  }),
  // 24 - rohan, DRAFT
  p({
    owner: "rohan",
    title: "Kharadi 2 BHK flat - draft listing",
    description:
      "Two-bedroom flat near EON IT Park, Kharadi. Listing details still being finalised - photos to follow after the flat is staged next week. Great light, modular kitchen, two covered car parks.",
    listingType: "SALE",
    propertyType: "APARTMENT",
    status: "DRAFT",
    price: 9800000,
    deposit: 50000,
    address: "Flat 305, Marvel Zephyr, Kharadi",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411014",
    lat: 18.5515,
    lng: 73.9345,
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    interiorArea: 1150,
    lotArea: null,
    yearBuilt: 2015,
    furnished: "UNFURNISHED",
    amenities: ["car-parking", "lift"],
    images: 1,
    views: 0,
    daysAgo: 2,
  }),
  // 25 - meera, REJECTED residential plot (LISTING_REJECTED notification + audit reference this index)
  p({
    owner: "meera",
    title: "Sarjapur Road residential plot - rejected listing",
    description: "30x50 plot in a developing layout off Sarjapur Road. Details were incomplete when submitted; the listing needs a survey sketch and confirmed dimensions before it can go live.",
    listingType: "SALE",
    propertyType: "PLOT_RESIDENTIAL",
    status: "REJECTED",
    price: 4500000,
    deposit: 25000,
    address: "Site 12, Sri Lakshmi Layout, Sarjapur Road",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "562125",
    lat: 12.8604,
    lng: 77.7869,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    interiorArea: null,
    lotArea: 1500,
    yearBuilt: null,
    furnished: "UNFURNISHED",
    amenities: [],
    images: 1,
    views: 4,
    daysAgo: 14,
    rejectionReason: "Please attach the survey sketch and confirm the plot dimensions before resubmitting.",
  }),
  // 26 - meera, featured industrial plot for sale
  p({
    owner: "meera",
    title: "3-acre industrial plot on the Bengaluru-Chennai expressway, Hoskote",
    description:
      "Level, cleared 3-acre site in a KIADB-approved industrial area two minutes from the Bengaluru-Chennai expressway and forty from the airport. Three-phase power, BESCOM connection and a borewell at the boundary; converted (non-agricultural) land with clear title and an approved layout plan.\n\nSuitable for a warehouse, cold storage or a light-manufacturing unit. The adjoining 2-acre parcel can be bundled.",
    listingType: "SALE",
    propertyType: "PLOT_INDUSTRIAL",
    status: "ACTIVE",
    price: 65000000,
    deposit: 200000,
    address: "Plot 4, KIADB Industrial Area, Hoskote",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "562114",
    lat: 13.0707,
    lng: 77.798,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    interiorArea: null,
    lotArea: 130680,
    yearBuilt: null,
    furnished: "UNFURNISHED",
    amenities: ["road-access", "compound-wall", "borewell", "power-backup"],
    featured: true,
    images: 2,
    views: 168,
    daysAgo: 4,
  }),
  // 27 - rohan, industrial site for rent
  p({
    owner: "rohan",
    title: "Fenced industrial site with shed in Chakan MIDC",
    description:
      "1.6-acre fenced and paved industrial site in Chakan MIDC Phase 2 with a 4,000 sq ft steel shed, offered on a long-term lease. Heavy-duty gate, floodlighting, three-phase power and a truck turnaround.\n\nMIDC industrial zoning. Ideal for an equipment yard, materials storage or light fabrication. Minimum 3-year term.",
    listingType: "RENT",
    propertyType: "PLOT_INDUSTRIAL",
    status: "ACTIVE",
    price: 185000,
    deposit: 185000,
    address: "Plot D-22, MIDC Phase 2, Chakan",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "410501",
    lat: 18.7606,
    lng: 73.8636,
    bedrooms: 0,
    bathrooms: 1,
    parking: 12,
    interiorArea: 4000,
    lotArea: 69696,
    yearBuilt: 1998,
    furnished: "UNFURNISHED",
    amenities: ["compound-wall", "road-access", "power-backup", "gated-security"],
    images: 2,
    views: 74,
    daysAgo: 12,
  }),
  // 28 - arjun, commercial plot for sale
  p({
    owner: "arjun",
    title: "Commercial plot on the OMR IT corridor, Siruseri",
    description:
      "10,000 sq ft commercial plot with 120 feet of frontage on Old Mahabalipuram Road, opposite the SIPCOT IT park. CMDA-approved for commercial use with FSI suitable for a G+4 office or retail building.\n\nClear title, patta and encumbrance certificate available. Metro phase 2 station planned within 500 metres.",
    listingType: "SALE",
    propertyType: "PLOT_COMMERCIAL",
    status: "ACTIVE",
    price: 48000000,
    deposit: 200000,
    address: "Plot 5, OMR Service Road, Siruseri",
    city: "Chennai",
    state: "Tamil Nadu",
    postalCode: "603103",
    lat: 12.823,
    lng: 80.227,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    interiorArea: null,
    lotArea: 10000,
    yearBuilt: null,
    furnished: "UNFURNISHED",
    amenities: ["road-access", "corner-plot", "compound-wall"],
    images: 2,
    views: 92,
    daysAgo: 6,
  }),
  // 29 - kavya, semi-commercial plot for sale
  p({
    owner: "kavya",
    title: "Semi-commercial corner plot on the main road, Kompally",
    description:
      "4,000 sq ft corner plot on a 60-foot main road in Kompally, zoned for mixed use: shops or a clinic on the ground floor with residences above. HMDA-approved layout with underground drainage, wide tar roads and street lighting.\n\nBorewell in place, compound wall on three sides. Clear title with link documents available.",
    listingType: "SALE",
    propertyType: "PLOT_SEMI_COMMERCIAL",
    status: "ACTIVE",
    price: 21000000,
    deposit: 100000,
    address: "Plot 61, Sai Krishna Enclave, Main Road, Kompally",
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500014",
    lat: 17.5426,
    lng: 78.4851,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    interiorArea: null,
    lotArea: 4000,
    yearBuilt: null,
    furnished: "UNFURNISHED",
    amenities: ["corner-plot", "road-access", "borewell", "compound-wall"],
    images: 2,
    views: 61,
    daysAgo: 9,
  }),
];
