// Static seed content: amenities, demo users and realistic listings.

export const AMENITIES = [
  { slug: "air-conditioning", name: "Air conditioning", category: "Comfort" },
  { slug: "central-heating", name: "Central heating", category: "Comfort" },
  { slug: "fireplace", name: "Fireplace", category: "Comfort" },
  { slug: "hardwood-floors", name: "Hardwood floors", category: "Interior" },
  { slug: "walk-in-closet", name: "Walk-in closet", category: "Interior" },
  { slug: "home-office", name: "Home office", category: "Interior" },
  { slug: "renovated-kitchen", name: "Renovated kitchen", category: "Interior" },
  { slug: "dishwasher", name: "Dishwasher", category: "Interior" },
  { slug: "in-unit-laundry", name: "In-unit laundry", category: "Interior" },
  { slug: "garage", name: "Garage", category: "Outdoor" },
  { slug: "garden", name: "Garden", category: "Outdoor" },
  { slug: "balcony", name: "Balcony", category: "Outdoor" },
  { slug: "terrace", name: "Terrace", category: "Outdoor" },
  { slug: "swimming-pool", name: "Swimming pool", category: "Outdoor" },
  { slug: "ev-charging", name: "EV charging", category: "Outdoor" },
  { slug: "elevator", name: "Elevator", category: "Building" },
  { slug: "concierge", name: "Concierge", category: "Building" },
  { slug: "gym", name: "Gym", category: "Building" },
  { slug: "storage-unit", name: "Storage unit", category: "Building" },
  { slug: "security-system", name: "Security system", category: "Building" },
  { slug: "pet-friendly", name: "Pet friendly", category: "Lifestyle" },
  { slug: "solar-panels", name: "Solar panels", category: "Lifestyle" },
  { slug: "high-speed-internet", name: "High-speed internet", category: "Lifestyle" },
  { slug: "water-view", name: "Water view", category: "Lifestyle" },
];

export type SeedUser = {
  key: string;
  name: string;
  email: string;
  role: "BUYER" | "SELLER" | "AGENT" | "ADMIN";
  verified: boolean;
  status?: "ACTIVE" | "SUSPENDED";
  profile: { phone?: string; bio?: string; company?: string; location?: string; website?: string };
};

export const USERS: SeedUser[] = [
  {
    key: "admin",
    name: "Avery Admin",
    email: "admin@haven.local",
    role: "ADMIN",
    verified: true,
    profile: { location: "Remote", bio: "Platform administrator for the Haven Estates demo.", company: "Haven Estates" },
  },
  {
    key: "maria",
    name: "Maria Santos",
    email: "maria.santos@haven.local",
    role: "SELLER",
    verified: true,
    profile: { phone: "+1 512 555 0142", location: "Austin, TX", bio: "Selling the family homes we have lovingly renovated over the years. Fast, honest replies." },
  },
  {
    key: "james",
    name: "James Okafor",
    email: "james.okafor@haven.local",
    role: "AGENT",
    verified: true,
    profile: { phone: "+1 303 555 0188", company: "Okafor Realty", location: "Denver, CO", website: "https://example.com/okafor-realty", bio: "Licensed agent with 12 years in the Front Range market. Specialising in family homes and townhouses." },
  },
  {
    key: "lena",
    name: "Lena Fischer",
    email: "lena.fischer@haven.local",
    role: "SELLER",
    verified: true,
    profile: { phone: "+1 503 555 0121", location: "Portland, OR", bio: "Architect turned landlord. My rentals are energy efficient and pet friendly." },
  },
  {
    key: "daniel",
    name: "Daniel Kim",
    email: "daniel.kim@haven.local",
    role: "AGENT",
    verified: true,
    profile: { phone: "+1 206 555 0177", company: "Kim & Co Estates", location: "Seattle, WA", website: "https://example.com/kim-estates", bio: "Boutique agency covering Seattle, San Diego and Miami waterfront properties." },
  },
  {
    key: "priya",
    name: "Priya Nair",
    email: "priya.nair@haven.local",
    role: "BUYER",
    verified: true,
    profile: { phone: "+1 512 555 0199", location: "Austin, TX", bio: "First-time buyer looking for a 3-bed with a garden." },
  },
  {
    key: "marcus",
    name: "Marcus Dean",
    email: "marcus.dean@haven.local",
    role: "BUYER",
    verified: true,
    profile: { location: "Denver, CO", bio: "Relocating for work - need somewhere with a home office and fast internet." },
  },
  {
    key: "sofia",
    name: "Sofia Rossi",
    email: "sofia.rossi@haven.local",
    role: "BUYER",
    verified: true,
    profile: { location: "Miami, FL", bio: "Investor comparing rental yields across the Sun Belt." },
  },
  {
    key: "tom",
    name: "Tom Nguyen",
    email: "tom.nguyen@haven.local",
    role: "BUYER",
    verified: true,
    profile: { location: "Seattle, WA" },
  },
  {
    key: "newbie",
    name: "Nadia Newcomer",
    email: "new.user@haven.local",
    role: "BUYER",
    verified: false,
    profile: {},
  },
  {
    key: "suspended",
    name: "Sam Spammer",
    email: "suspended@haven.local",
    role: "SELLER",
    verified: true,
    status: "SUSPENDED",
    profile: { location: "Unknown" },
  },
];

export type SeedProperty = {
  owner: string;
  title: string;
  description: string;
  listingType: "SALE" | "RENT";
  propertyType: "HOUSE" | "APARTMENT" | "CONDO" | "TOWNHOUSE" | "LAND" | "COMMERCIAL" | "OTHER";
  status: "DRAFT" | "PENDING_REVIEW" | "ACTIVE" | "UNDER_OFFER" | "RESERVED" | "SOLD" | "RENTED" | "REJECTED" | "ARCHIVED";
  price: number;
  deposit: number;
  address: string;
  city: string;
  state: string;
  postalCode: string;
  lat: number;
  lng: number;
  bedrooms: number;
  bathrooms: number;
  parking: number;
  interiorArea: number | null;
  lotArea: number | null;
  yearBuilt: number | null;
  furnished: "UNFURNISHED" | "SEMI_FURNISHED" | "FURNISHED";
  amenities: string[];
  featured?: boolean;
  images: number;
  views: number;
  daysAgo: number;
  rejectionReason?: string;
};

const p = (input: SeedProperty) => input;

export const PROPERTIES: SeedProperty[] = [
  p({
    owner: "maria",
    title: "Sunlit 3-bed craftsman with a private garden",
    description:
      "A lovingly restored 1928 craftsman on a quiet, tree-lined street in Hyde Park. Original hardwood floors run through the light-filled living room and into a renovated kitchen with quartz counters, a gas range and a walk-in pantry.\n\nThree generous bedrooms upstairs share a spa-style bathroom, while the ground floor has a second bathroom and a flexible study that works as a home office or nursery. Outside, a deep private garden with mature pecan trees, a covered porch and a detached garage with EV charging.\n\nWalk to coffee shops, the farmers market and two highly rated schools. Roof replaced 2022, HVAC 2021.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 749000,
    deposit: 7500,
    address: "4112 Avenue F",
    city: "Austin",
    state: "TX",
    postalCode: "78751",
    lat: 30.3098,
    lng: -97.7276,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    interiorArea: 1880,
    lotArea: 7200,
    yearBuilt: 1928,
    furnished: "UNFURNISHED",
    amenities: ["hardwood-floors", "renovated-kitchen", "garden", "garage", "ev-charging", "home-office", "air-conditioning"],
    featured: true,
    images: 4,
    views: 412,
    daysAgo: 6,
  }),
  p({
    owner: "maria",
    title: "Modern East Austin townhouse with rooftop terrace",
    description:
      "Three-storey end-unit townhouse built in 2019 with a private rooftop terrace and downtown skyline views. Open-plan living on the second floor with floor-to-ceiling windows, a chef's kitchen and a powder room.\n\nTwo bedroom suites on the top floor, each with its own bathroom. Ground floor flex room, attached two-car garage and a fenced side yard. Low HOA covers exterior maintenance and landscaping.",
    listingType: "SALE",
    propertyType: "TOWNHOUSE",
    status: "ACTIVE",
    price: 615000,
    deposit: 6000,
    address: "2207 E 7th St, Unit B",
    city: "Austin",
    state: "TX",
    postalCode: "78702",
    lat: 30.2617,
    lng: -97.7194,
    bedrooms: 2,
    bathrooms: 2.5,
    parking: 2,
    interiorArea: 1640,
    lotArea: 2100,
    yearBuilt: 2019,
    furnished: "UNFURNISHED",
    amenities: ["terrace", "garage", "air-conditioning", "in-unit-laundry", "dishwasher", "high-speed-internet"],
    images: 3,
    views: 268,
    daysAgo: 12,
  }),
  p({
    owner: "maria",
    title: "Cosy 1-bed bungalow near Zilker Park",
    description:
      "Charming one-bedroom bungalow steps from Barton Springs. Vaulted ceilings, exposed beams and a wood-burning fireplace give the living room real character. Updated kitchen and bathroom, in-unit laundry and a covered patio for morning coffee.\n\nPerfect starter home or pied-à-terre. Off-street parking for one car.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 489000,
    deposit: 5000,
    address: "1718 Kinney Ave",
    city: "Austin",
    state: "TX",
    postalCode: "78704",
    lat: 30.2549,
    lng: -97.7674,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    interiorArea: 820,
    lotArea: 4300,
    yearBuilt: 1946,
    furnished: "SEMI_FURNISHED",
    amenities: ["fireplace", "in-unit-laundry", "garden", "pet-friendly"],
    images: 3,
    views: 190,
    daysAgo: 20,
  }),
  p({
    owner: "james",
    title: "Highlands family home with mountain views",
    description:
      "Spacious four-bedroom home in Denver's Highlands with unobstructed views of the Front Range from the primary suite and back deck. Main level features a great room with a stone fireplace, formal dining and a kitchen with a large island and double ovens.\n\nFinished basement with a media room, guest bedroom and wet bar. Three-car garage, xeriscaped front yard and a large back lawn with a fire pit. Highly rated schools within walking distance.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 1195000,
    deposit: 12000,
    address: "3535 W 32nd Ave",
    city: "Denver",
    state: "CO",
    postalCode: "80211",
    lat: 39.7614,
    lng: -105.0341,
    bedrooms: 4,
    bathrooms: 3.5,
    parking: 3,
    interiorArea: 3450,
    lotArea: 6300,
    yearBuilt: 2008,
    furnished: "UNFURNISHED",
    amenities: ["fireplace", "garage", "garden", "central-heating", "air-conditioning", "home-office", "security-system"],
    featured: true,
    images: 4,
    views: 587,
    daysAgo: 4,
  }),
  p({
    owner: "james",
    title: "LoDo loft with exposed brick and city views",
    description:
      "Authentic warehouse conversion in Lower Downtown: 14-foot timber ceilings, exposed brick, oversized industrial windows and polished concrete floors. Open kitchen with stainless appliances, a large bedroom with custom closets and a spa bathroom.\n\nBuilding offers a rooftop deck, gym and 24-hour concierge. One deeded parking space in the secure garage. Coors Field and Union Station are two blocks away.",
    listingType: "SALE",
    propertyType: "CONDO",
    status: "UNDER_OFFER",
    price: 689000,
    deposit: 7000,
    address: "1720 Wynkoop St, #402",
    city: "Denver",
    state: "CO",
    postalCode: "80202",
    lat: 39.7532,
    lng: -105.0003,
    bedrooms: 1,
    bathrooms: 1.5,
    parking: 1,
    interiorArea: 1240,
    lotArea: null,
    yearBuilt: 1905,
    furnished: "UNFURNISHED",
    amenities: ["elevator", "concierge", "gym", "garage", "storage-unit", "high-speed-internet"],
    images: 3,
    views: 341,
    daysAgo: 25,
  }),
  p({
    owner: "james",
    title: "Renovated Wash Park duplex - live in one, rent the other",
    description:
      "Rare side-by-side duplex a block from Washington Park. Each unit has two bedrooms, one bathroom, a private entrance, laundry and its own fenced yard. Fully renovated in 2021 with new roofs, windows, electrical and plumbing.\n\nCurrently one unit is owner-occupied and the other rents for ₹2,650/month. Ideal for house-hacking or a long-term investment.",
    listingType: "SALE",
    propertyType: "OTHER",
    status: "ACTIVE",
    price: 985000,
    deposit: 10000,
    address: "890 S Gaylord St",
    city: "Denver",
    state: "CO",
    postalCode: "80209",
    lat: 39.6998,
    lng: -104.9548,
    bedrooms: 4,
    bathrooms: 2,
    parking: 2,
    interiorArea: 2400,
    lotArea: 6250,
    yearBuilt: 1952,
    furnished: "UNFURNISHED",
    amenities: ["garden", "in-unit-laundry", "central-heating", "renovated-kitchen"],
    images: 3,
    views: 223,
    daysAgo: 9,
  }),
  p({
    owner: "james",
    title: "Boulder foothills building lot with utilities",
    description:
      "1.2-acre gently sloping lot in the foothills west of Boulder with approved plans for a 3,200 sq ft passive house. Water, electricity and fibre are at the lot line; septic design is approved.\n\nSouth-facing with mountain views, mature ponderosa pines and direct trail access. Fifteen minutes to Pearl Street.",
    listingType: "SALE",
    propertyType: "LAND",
    status: "ACTIVE",
    price: 425000,
    deposit: 5000,
    address: "Lot 7, Sunshine Canyon Dr",
    city: "Boulder",
    state: "CO",
    postalCode: "80302",
    lat: 40.0294,
    lng: -105.3239,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    interiorArea: null,
    lotArea: 52272,
    yearBuilt: null,
    furnished: "UNFURNISHED",
    amenities: ["high-speed-internet"],
    images: 2,
    views: 98,
    daysAgo: 30,
  }),
  p({
    owner: "lena",
    title: "Bright 2-bed apartment in the Pearl District",
    description:
      "Corner apartment on the sixth floor of a LEED-certified building with floor-to-ceiling glass, a wraparound balcony and views of the Fremont Bridge. Two bedrooms, two bathrooms, a proper laundry room and a kitchen with induction cooking.\n\nBuilding amenities include a gym, bike room, package lockers and a shared rooftop garden. Rent includes water, sewer and high-speed fibre. Pets welcome with deposit. Twelve-month lease minimum.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 3450,
    deposit: 3450,
    address: "1130 NW 12th Ave, #612",
    city: "Portland",
    state: "OR",
    postalCode: "97209",
    lat: 45.5306,
    lng: -122.6834,
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    interiorArea: 1150,
    lotArea: null,
    yearBuilt: 2016,
    furnished: "UNFURNISHED",
    amenities: ["balcony", "elevator", "gym", "in-unit-laundry", "pet-friendly", "high-speed-internet", "ev-charging"],
    featured: true,
    images: 4,
    views: 730,
    daysAgo: 3,
  }),
  p({
    owner: "lena",
    title: "Furnished studio in Alberta Arts, all bills included",
    description:
      "Thoughtfully furnished studio above a bakery on Alberta Street. Murphy bed, built-in desk, compact kitchen with everything you need and a tiled shower room. Heat pump for heating and cooling.\n\nRent includes all utilities and gigabit internet. Available on three-month minimum terms - ideal for a work placement or a trial of the neighbourhood.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 1650,
    deposit: 1650,
    address: "2015 NE Alberta St, Apt 3",
    city: "Portland",
    state: "OR",
    postalCode: "97211",
    lat: 45.559,
    lng: -122.6432,
    bedrooms: 0,
    bathrooms: 1,
    parking: 0,
    interiorArea: 420,
    lotArea: null,
    yearBuilt: 1925,
    furnished: "FURNISHED",
    amenities: ["high-speed-internet", "air-conditioning", "central-heating"],
    images: 3,
    views: 502,
    daysAgo: 8,
  }),
  p({
    owner: "lena",
    title: "Energy-efficient 3-bed house in Sellwood",
    description:
      "Net-zero-ready family home with a 7 kW solar array, heat pump and triple-glazed windows - average utility bill under ₹40. Three bedrooms, two bathrooms, an open kitchen-living room that opens onto a landscaped garden with raised beds.\n\nDetached studio with power and heat works as an office or guest room. Two blocks from the Springwater Corridor trail. Twelve-month lease, pets considered.",
    listingType: "RENT",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 3900,
    deposit: 3900,
    address: "7714 SE 17th Ave",
    city: "Portland",
    state: "OR",
    postalCode: "97202",
    lat: 45.4693,
    lng: -122.648,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    interiorArea: 1720,
    lotArea: 5000,
    yearBuilt: 2015,
    furnished: "UNFURNISHED",
    amenities: ["solar-panels", "garden", "home-office", "in-unit-laundry", "pet-friendly", "ev-charging"],
    images: 3,
    views: 288,
    daysAgo: 15,
  }),
  p({
    owner: "lena",
    title: "Riverside 1-bed with balcony - South Waterfront",
    description:
      "Twelfth-floor one-bedroom with a west-facing balcony over the Willamette. Quartz kitchen, walk-in closet, in-unit laundry and a large bathroom. Building has a 24-hour concierge, gym, sauna and secure parking.\n\nCurrently tenanted; available from the first of next month.",
    listingType: "RENT",
    propertyType: "CONDO",
    status: "RENTED",
    price: 2450,
    deposit: 2450,
    address: "3601 S River Pkwy, #1207",
    city: "Portland",
    state: "OR",
    postalCode: "97239",
    lat: 45.4936,
    lng: -122.6716,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    interiorArea: 760,
    lotArea: null,
    yearBuilt: 2009,
    furnished: "UNFURNISHED",
    amenities: ["balcony", "concierge", "gym", "elevator", "water-view", "in-unit-laundry"],
    images: 2,
    views: 411,
    daysAgo: 60,
  }),
  p({
    owner: "daniel",
    title: "Queen Anne view home with a chef's kitchen",
    description:
      "Classic 1912 foursquare on the south slope of Queen Anne with sweeping views of Elliott Bay, the Space Needle and Mount Rainier. Restored period details - box beams, leaded glass, a curved staircase - paired with a fully modern kitchen and mechanicals.\n\nFour bedrooms including a top-floor primary suite with a private deck. Lower level has a family room, wine cellar and a separate-entrance guest suite. Two-car garage. Roof and sewer line new in 2023.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 2450000,
    deposit: 25000,
    address: "1520 8th Ave W",
    city: "Seattle",
    state: "WA",
    postalCode: "98119",
    lat: 47.6323,
    lng: -122.3684,
    bedrooms: 4,
    bathrooms: 3.5,
    parking: 2,
    interiorArea: 3900,
    lotArea: 5400,
    yearBuilt: 1912,
    furnished: "UNFURNISHED",
    amenities: ["water-view", "fireplace", "garage", "hardwood-floors", "renovated-kitchen", "garden", "security-system"],
    featured: true,
    images: 4,
    views: 902,
    daysAgo: 2,
  }),
  p({
    owner: "daniel",
    title: "Capitol Hill 2-bed condo, walk to light rail",
    description:
      "Top-floor two-bedroom in a well-run 2004 building on a quiet Capitol Hill street. Vaulted ceilings, gas fireplace, private balcony and a bright open kitchen. Both bedrooms fit king beds; the primary has an ensuite.\n\nHOA includes water, sewer, garbage and earthquake insurance. Secure garage parking and a storage locker. Light rail, Cal Anderson Park and dozens of restaurants within five minutes.",
    listingType: "SALE",
    propertyType: "CONDO",
    status: "ACTIVE",
    price: 725000,
    deposit: 7500,
    address: "1711 E Olive Way, #501",
    city: "Seattle",
    state: "WA",
    postalCode: "98102",
    lat: 47.6194,
    lng: -122.3238,
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    interiorArea: 1080,
    lotArea: null,
    yearBuilt: 2004,
    furnished: "UNFURNISHED",
    amenities: ["balcony", "fireplace", "elevator", "garage", "storage-unit", "pet-friendly"],
    images: 3,
    views: 377,
    daysAgo: 11,
  }),
  p({
    owner: "daniel",
    title: "Ballard townhouse with rooftop deck and Olympic views",
    description:
      "Light-filled 2020 townhouse with a private rooftop deck facing the Olympic Mountains. Three levels: garage and flex room, open-plan living with a balcony, and two bedroom suites up top. Heat pump, tankless water heater, EV-ready garage.\n\nNo HOA. Walk to the Ballard Locks, the farmers market and the Burke-Gilman trail.",
    listingType: "SALE",
    propertyType: "TOWNHOUSE",
    status: "ACTIVE",
    price: 869000,
    deposit: 9000,
    address: "5615 17th Ave NW, Unit C",
    city: "Seattle",
    state: "WA",
    postalCode: "98107",
    lat: 47.6697,
    lng: -122.3782,
    bedrooms: 2,
    bathrooms: 2.5,
    parking: 1,
    interiorArea: 1490,
    lotArea: 1400,
    yearBuilt: 2020,
    furnished: "UNFURNISHED",
    amenities: ["terrace", "balcony", "garage", "ev-charging", "air-conditioning", "in-unit-laundry"],
    images: 3,
    views: 254,
    daysAgo: 17,
  }),
  p({
    owner: "daniel",
    title: "La Jolla ocean-view condo with resort amenities",
    description:
      "Fully furnished two-bedroom on the fourth floor of an oceanfront community. Wake up to whitewater views from the bedroom and living room, and watch the sunset from the covered lanai.\n\nRemodelled in 2022 with a quartz kitchen, wide-plank floors and spa bathrooms. Community features two pools, tennis courts, a gym and gated parking. Perfect second home or turnkey rental.",
    listingType: "SALE",
    propertyType: "CONDO",
    status: "RESERVED",
    price: 1650000,
    deposit: 16500,
    address: "939 Coast Blvd, #4F",
    city: "San Diego",
    state: "CA",
    postalCode: "92037",
    lat: 32.8481,
    lng: -117.2749,
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    interiorArea: 1380,
    lotArea: null,
    yearBuilt: 1974,
    furnished: "FURNISHED",
    amenities: ["water-view", "swimming-pool", "gym", "balcony", "elevator", "security-system", "air-conditioning"],
    images: 4,
    views: 645,
    daysAgo: 40,
  }),
  p({
    owner: "daniel",
    title: "North Park Spanish bungalow with casita",
    description:
      "1930s Spanish revival bungalow on a corner lot in North Park with a separate one-bedroom casita (currently rented at ₹1,900/month). Main house has two bedrooms, an updated kitchen with Saltillo tile, arched doorways and a wood-burning fireplace.\n\nDrought-tolerant landscaping, a citrus grove and a covered patio with a built-in grill. Walk to 30th Street's breweries and restaurants.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 1295000,
    deposit: 13000,
    address: "3305 Granada Ave",
    city: "San Diego",
    state: "CA",
    postalCode: "92104",
    lat: 32.7422,
    lng: -117.1326,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    interiorArea: 1760,
    lotArea: 6500,
    yearBuilt: 1934,
    furnished: "UNFURNISHED",
    amenities: ["fireplace", "garden", "renovated-kitchen", "hardwood-floors", "pet-friendly"],
    images: 3,
    views: 318,
    daysAgo: 7,
  }),
  p({
    owner: "daniel",
    title: "Brickell high-rise 1-bed with bay views",
    description:
      "Twenty-eighth floor one-bedroom plus den in a full-service Brickell tower. Floor-to-ceiling glass frames Biscayne Bay; the wraparound balcony is perfect for sunrise coffee. Italian kitchen, smart-home lighting, in-unit laundry.\n\nAmenities include an infinity pool, spa, gym, co-working lounge and valet parking. Available furnished or unfurnished on a twelve-month lease.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 4200,
    deposit: 4200,
    address: "1300 Brickell Bay Dr, #2804",
    city: "Miami",
    state: "FL",
    postalCode: "33131",
    lat: 25.7615,
    lng: -80.1893,
    bedrooms: 1,
    bathrooms: 1.5,
    parking: 1,
    interiorArea: 940,
    lotArea: null,
    yearBuilt: 2018,
    furnished: "SEMI_FURNISHED",
    amenities: ["water-view", "swimming-pool", "gym", "concierge", "elevator", "balcony", "air-conditioning", "in-unit-laundry"],
    featured: true,
    images: 3,
    views: 812,
    daysAgo: 5,
  }),
  p({
    owner: "daniel",
    title: "Coconut Grove tropical retreat with pool",
    description:
      "Single-storey mid-century home hidden behind lush landscaping in the heart of Coconut Grove. Four bedrooms, three bathrooms, a great room with vaulted ceilings and walls of glass opening to a saltwater pool and outdoor kitchen.\n\nImpact windows, a new metal roof (2023) and a whole-house generator. Two-car garage plus boat trailer parking. Bike to the marina and the village.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 2890000,
    deposit: 25000,
    address: "3901 Kumquat Ave",
    city: "Miami",
    state: "FL",
    postalCode: "33133",
    lat: 25.7256,
    lng: -80.2492,
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    interiorArea: 2950,
    lotArea: 12000,
    yearBuilt: 1962,
    furnished: "UNFURNISHED",
    amenities: ["swimming-pool", "garden", "garage", "air-conditioning", "security-system", "renovated-kitchen"],
    images: 4,
    views: 466,
    daysAgo: 13,
  }),
  p({
    owner: "maria",
    title: "East Nashville cottage with a music room",
    description:
      "Updated 1940s cottage in Lockeland Springs with a soundproofed music room in the converted garage. Two bedrooms, one and a half bathrooms, original heart-pine floors and a screened porch overlooking a fenced back yard.\n\nNew HVAC (2022) and tankless water heater. Five Points bars, restaurants and Shelby Park are a short walk away.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "ACTIVE",
    price: 565000,
    deposit: 6000,
    address: "1611 Holly St",
    city: "Nashville",
    state: "TN",
    postalCode: "37206",
    lat: 36.1752,
    lng: -86.7391,
    bedrooms: 2,
    bathrooms: 1.5,
    parking: 1,
    interiorArea: 1320,
    lotArea: 6100,
    yearBuilt: 1942,
    furnished: "UNFURNISHED",
    amenities: ["hardwood-floors", "garden", "home-office", "air-conditioning", "pet-friendly"],
    images: 3,
    views: 201,
    daysAgo: 18,
  }),
  p({
    owner: "james",
    title: "Logan Square 3-flat - fully leased investment",
    description:
      "Classic Chicago greystone three-flat on a wide Logan Square lot. Each unit has three bedrooms, one bathroom, a formal dining room and rear deck access. Fully leased with a gross annual rent of ₹84,000 and long-term tenants.\n\nSeparate utilities, newer boilers and a two-car garage. Two blocks from the Blue Line and the 606 trail.",
    listingType: "SALE",
    propertyType: "COMMERCIAL",
    status: "ACTIVE",
    price: 1150000,
    deposit: 12000,
    address: "2634 N Kedzie Blvd",
    city: "Chicago",
    state: "IL",
    postalCode: "60647",
    lat: 41.9296,
    lng: -87.7073,
    bedrooms: 9,
    bathrooms: 3,
    parking: 2,
    interiorArea: 4200,
    lotArea: 3750,
    yearBuilt: 1908,
    furnished: "UNFURNISHED",
    amenities: ["garage", "central-heating", "storage-unit"],
    images: 3,
    views: 156,
    daysAgo: 22,
  }),
  p({
    owner: "james",
    title: "West Loop penthouse with private terrace",
    description:
      "Two-bedroom penthouse in a boutique West Loop building with a 600 sq ft private terrace and skyline views. Ten-foot ceilings, wide-plank oak floors, a Wolf/Sub-Zero kitchen and a primary suite with a soaking tub.\n\nHeated garage parking for two cars included. Steps from Randolph Street restaurants and Fulton Market.",
    listingType: "SALE",
    propertyType: "CONDO",
    status: "SOLD",
    price: 1475000,
    deposit: 15000,
    address: "1115 W Washington Blvd, PH2",
    city: "Chicago",
    state: "IL",
    postalCode: "60607",
    lat: 41.8831,
    lng: -87.6553,
    bedrooms: 2,
    bathrooms: 2.5,
    parking: 2,
    interiorArea: 1900,
    lotArea: null,
    yearBuilt: 2017,
    furnished: "UNFURNISHED",
    amenities: ["terrace", "elevator", "garage", "renovated-kitchen", "hardwood-floors"],
    images: 3,
    views: 720,
    daysAgo: 75,
  }),
  p({
    owner: "lena",
    title: "Back Bay brownstone garden apartment",
    description:
      "Garden-level one-bedroom in a Commonwealth Avenue brownstone with a private patio. Exposed brick, a decorative fireplace, high ceilings and an updated galley kitchen. Laundry in the building and a storage cage.\n\nHeat and hot water included. Steps to the Public Garden, Newbury Street and the Green Line.",
    listingType: "RENT",
    propertyType: "APARTMENT",
    status: "ACTIVE",
    price: 3100,
    deposit: 3100,
    address: "233 Commonwealth Ave, Unit G",
    city: "Boston",
    state: "MA",
    postalCode: "02116",
    lat: 42.3521,
    lng: -71.0797,
    bedrooms: 1,
    bathrooms: 1,
    parking: 0,
    interiorArea: 680,
    lotArea: null,
    yearBuilt: 1885,
    furnished: "UNFURNISHED",
    amenities: ["fireplace", "terrace", "central-heating", "storage-unit"],
    images: 2,
    views: 344,
    daysAgo: 10,
  }),
  p({
    owner: "maria",
    title: "Arcadia ranch with casita and mountain views",
    description:
      "Single-level ranch on a half-acre in Arcadia with Camelback Mountain views from the back yard. Four bedrooms plus a detached casita, a resort-style pool, citrus trees and a covered ramada with an outdoor kitchen.\n\nRemodelled kitchen with a 48-inch range, new roof (2024) and owned solar panels. RV gate and a three-car garage.",
    listingType: "SALE",
    propertyType: "HOUSE",
    status: "PENDING_REVIEW",
    price: 1875000,
    deposit: 18000,
    address: "4425 E Calle Redonda",
    city: "Phoenix",
    state: "AZ",
    postalCode: "85018",
    lat: 33.5028,
    lng: -111.9836,
    bedrooms: 4,
    bathrooms: 3,
    parking: 3,
    interiorArea: 3200,
    lotArea: 21780,
    yearBuilt: 1968,
    furnished: "UNFURNISHED",
    amenities: ["swimming-pool", "solar-panels", "garage", "garden", "air-conditioning", "renovated-kitchen"],
    images: 3,
    views: 0,
    daysAgo: 1,
  }),
  p({
    owner: "daniel",
    title: "Downtown Phoenix live/work loft",
    description:
      "Ground-floor live/work loft in the Roosevelt Row arts district with a commercial storefront, a mezzanine bedroom and a polished concrete open plan. Zoned for retail or studio use.\n\nTwelve-foot roll-up glass door, 200-amp service and a private rear patio. Light rail one block away.",
    listingType: "RENT",
    propertyType: "COMMERCIAL",
    status: "PENDING_REVIEW",
    price: 2800,
    deposit: 2800,
    address: "912 N 3rd St",
    city: "Phoenix",
    state: "AZ",
    postalCode: "85004",
    lat: 33.4586,
    lng: -112.0691,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    interiorArea: 1100,
    lotArea: null,
    yearBuilt: 2006,
    furnished: "UNFURNISHED",
    amenities: ["air-conditioning", "high-speed-internet", "terrace"],
    images: 2,
    views: 0,
    daysAgo: 0,
  }),
  p({
    owner: "james",
    title: "Cherry Creek condo - draft listing",
    description:
      "Two-bedroom condo near Cherry Creek North. Listing details still being finalised - photos to follow after staging next week. Great light, updated kitchen, two garage spaces.",
    listingType: "SALE",
    propertyType: "CONDO",
    status: "DRAFT",
    price: 640000,
    deposit: 6500,
    address: "100 Detroit St, #305",
    city: "Denver",
    state: "CO",
    postalCode: "80206",
    lat: 39.7185,
    lng: -104.9532,
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    interiorArea: 1300,
    lotArea: null,
    yearBuilt: 1999,
    furnished: "UNFURNISHED",
    amenities: ["garage", "elevator"],
    images: 1,
    views: 0,
    daysAgo: 2,
  }),
  p({
    owner: "maria",
    title: "Lakeway hillside lot - rejected listing",
    description: "Half-acre hillside lot above Lake Travis. Details were incomplete when submitted; the listing needs a verified survey and correct acreage before it can go live.",
    listingType: "SALE",
    propertyType: "LAND",
    status: "REJECTED",
    price: 210000,
    deposit: 2500,
    address: "Lot 12, Lakeway Dr",
    city: "Lakeway",
    state: "TX",
    postalCode: "78734",
    lat: 30.3638,
    lng: -97.9797,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    interiorArea: null,
    lotArea: 21780,
    yearBuilt: null,
    furnished: "UNFURNISHED",
    amenities: [],
    images: 1,
    views: 4,
    daysAgo: 14,
    rejectionReason: "Please attach the survey and confirm the lot size before resubmitting.",
  }),
];
